add python plugin for smallfile
arcalot/arcaflow-plugins pull request #4
Opened 2022-08-11 11:52 UTC by dustinblack

## Changes introduced with this PR

Adds a python plugin for the smallfile benchmark utility

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-08-11 21:10 UTC, dustinblack commented on python/smallfile_plugin/smallfile_plugin.py
> +    top: str
Is it fair to just point to the smallfile documentation here since these are passthrough parameters?

2022-08-17 21:02 UTC, mfleader requested changes

2022-08-17 21:22 UTC, dustinblack commented on python/smallfile/Dockerfile
> +LABEL org.opencontainers.image.source="https://github.com/arcalot/arcaflow-plugins/tree/main/python/smallfile"
According to our README file:

> `org.opencontainers.image.source`: a link to the target directory in the main branch of this repository.

2022-08-19 10:20 UTC, dustinblack commented
squashed

2022-08-19 12:53 UTC, mfleader approved these changes

2022-08-19 13:25 UTC, merged